# Generated by Django 5.0.14 on 2025-10-20 15:53

import django.db.models.deletion
from django.db import migrations, models


def find(list_, predicate):
    return next((n for n in list_ if predicate(n)), None)


def add_node_to_graph(graph, nodes, current_node):
    graph[str(current_node.id)] = {}

    next_nodes = [n for n in nodes if n.previous_node_id == current_node.id]
    if next_nodes:
        graph[str(current_node.id)]["next"] = {
            n.previous_node_output: [n.id] for n in next_nodes
        }

    for next_node in next_nodes:
        add_node_to_graph(graph, nodes, next_node)


def forward(apps, schema_editor):
    Workflow = apps.get_model("automation", "automationworkflow")
    AutomationNode = apps.get_model("automation", "automationnode")

    all_nodes = list(AutomationNode.objects.filter(trashed=False))

    for workflow in Workflow.objects.all():
        graph = {}

        nodes = [n for n in all_nodes if n.workflow_id == workflow.id]
        trigger = find(nodes, lambda n: n.previous_node_id is None)

        if trigger:
            graph["0"] = trigger.id
            add_node_to_graph(graph, nodes, trigger)

        workflow.graph = graph
        workflow.save(update_fields=["graph"])


def reverse(apps, schema_editor):
    Workflow = apps.get_model("automation", "automationworkflow")
    AutomationNode = apps.get_model("automation", "automationnode")

    for workflow in Workflow.objects.all():
        graph = workflow.graph
        for key, info in graph.items():
            if key == "0":
                continue
            for output, nodes in info.get("next", {}).items():
                AutomationNode.objects.filter(id__in=nodes).update(
                    previous_node_id=key, previous_node_output=output
                )


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0020_corehttptriggernode"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoreIteratorActionNode",
            fields=[
                (
                    "automationnode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="automation.automationnode",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("automation.automationnode",),
        ),
        migrations.AlterModelOptions(
            name="automationnode",
            options={"ordering": ("id",)},
        ),
        migrations.RemoveField(
            model_name="automationnode",
            name="order",
        ),
        migrations.RemoveField(
            model_name="automationnode",
            name="parent_node",
        ),
        migrations.AddField(
            model_name="automationworkflow",
            name="graph",
            field=models.JSONField(default=dict, help_text="Contains the node graph."),
        ),
        migrations.RunPython(forward, reverse),
        migrations.RemoveField(
            model_name="automationnode",
            name="previous_node",
        ),
        migrations.RemoveField(
            model_name="automationnode",
            name="previous_node_output",
        ),
    ]
