# Generated by Django 5.0.13 on 2025-09-10 12:05

import django.db.models.deletion
from django.db import migrations, models

import baserow.core.formula.field


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0102_service_sample_data"),
        ("integrations", "0021_migrate_to_formula_field_objects"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoreIteratorService",
            fields=[
                (
                    "service_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.service",
                    ),
                ),
                (
                    "source",
                    baserow.core.formula.field.FormulaField(
                        blank=True, help_text="The path of the array."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.service",),
        ),
    ]
