# Generated by Django 5.0.14 on 2025-11-03 22:12

import django.db.models.deletion
from django.db import migrations, models

import baserow.core.formula.field


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0106_schemaoperation"),
        ("integrations", "0022_coreiteratorservice"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAgentService",
            fields=[
                (
                    "service_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.service",
                    ),
                ),
                (
                    "ai_generative_ai_type",
                    models.CharField(
                        help_text='The generative AI type (e.g. "openai", "anthropic", "mistral")',
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "ai_generative_ai_model",
                    models.CharField(
                        help_text='The specific model name (e.g. "gpt-4", "claude-3-opus")',
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "ai_output_type",
                    models.CharField(
                        choices=[("text", "Text"), ("choice", "Choice")],
                        default="text",
                        max_length=32,
                    ),
                ),
                ("ai_temperature", models.FloatField(null=True)),
                (
                    "ai_prompt",
                    baserow.core.formula.field.FormulaField(
                        blank=True, default="", null=True
                    ),
                ),
                ("ai_choices", models.JSONField(blank=True, default=list)),
            ],
            options={
                "abstract": False,
            },
            bases=("core.service",),
        ),
        migrations.CreateModel(
            name="AIIntegration",
            fields=[
                (
                    "integration_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.integration",
                    ),
                ),
                ("ai_settings", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
            bases=("core.integration",),
        ),
    ]
