# Generated by Django 5.0.14 on 2025-11-04 11:20

import django.db.models.deletion
from django.db import migrations, models

import baserow.core.formula.field


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0106_schemaoperation"),
        ("integrations", "0023_aiagentservice_aiintegration"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackBotIntegration",
            fields=[
                (
                    "integration_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.integration",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="The Bot User OAuth Token listed in your Slack bot's OAuth & Permissions page.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.integration",),
        ),
        migrations.CreateModel(
            name="SlackWriteMessageService",
            fields=[
                (
                    "service_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.service",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        help_text="The Slack channel ID where the message will be sent.",
                        max_length=80,
                    ),
                ),
                (
                    "text",
                    baserow.core.formula.field.FormulaField(
                        blank=True,
                        default="",
                        help_text="The text content of the Slack message.",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.service",),
        ),
    ]
