# Generated by Django 5.0.14 on 2025-09-29 09:33

import django.db.models.deletion
from django.db import migrations, models

import baserow.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0105_trashentry_trash_operation_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchemaOperation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                (
                    "operation",
                    models.CharField(
                        help_text="A unique identifier for the operation that was applied.",
                        max_length=64,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="The content type of the model that the operation was applied to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "unique_together": {("content_type_id", "operation")},
            },
        ),
    ]
