# Generated by Django 5.0.14 on 2025-10-24 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import baserow.core.fields
import baserow.core.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0106_schemaoperation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TwoFactorAuthProviderModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_auth_providers",
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User that setup 2fa with this provider",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_auth_providers",
                        to=settings.AUTH_USER_MODEL,
                        unique=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                baserow.core.mixins.PolymorphicContentTypeMixin,
                baserow.core.mixins.WithRegistry,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="TOTPAuthProviderModel",
            fields=[
                (
                    "twofactorauthprovidermodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.twofactorauthprovidermodel",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("secret", models.CharField(help_text="base32 secret", max_length=32)),
                ("provisioning_url", models.CharField(max_length=255)),
                ("provisioning_qr_code", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("core.twofactorauthprovidermodel",),
        ),
        migrations.CreateModel(
            name="TwoFactorAuthRecoveryCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="SHA-256 hash of the recovery code", max_length=64
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User that setup 2fa with recovery codes",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_recovery_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
